### ISSUE TITLE
mirage-xen does not work with OCaml 4.05

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-platform#194]
Linking the noop example from mirage-skeleton gives:

```
$ make
mirage build
_build/main.native.o: In function `camlBigarray__map_file_inner_1994':
/home/user/.opam/4.05.0/build/ocaml/otherlibs/bigarray/bigarray.ml:137: undefined reference to `caml_ba_map_file'
_build/main.native.o: In function `camlBigarray__49':
:(.data+0x67c70): undefined reference to `caml_ba_map_file'
```

**Comment by talex5** [comment]
So I guess this is due to this check in mirage-xen, which clears `BIGARRAY_OBJ` on 4.05:

```
4.04.2)
  echo Applying OCaml 4.04 config
  cp config/version-404.h ocaml-src/byterun/caml/version.h
  BIGARRAY_OBJ="mmap_unix.o"
  ;;
4.05.*)
  echo Applying OCaml 4.05 config
  cp config/version-405.h ocaml-src/byterun/caml/version.h
  BIGARRAY_OBJ=""
  CFLAGS="-D__ANDROID__"
  ;;
```
https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/build.sh#L53

But why was this changed? @avsm?

**Comment by talex5** [comment]
Also, replacing the Mini-OS CFLAGS with `-D__ANDROID__` probably isn't going to work.
