### PR TITLE
Fix mirage-xen on OCaml 4.05

### LINKED ISSUE #194: mirage-xen does not work with OCaml 4.05
Linking the noop example from mirage-skeleton gives:

```
$ make
mirage build
_build/main.native.o: In function `camlBigarray__map_file_inner_1994':
/home/user/.opam/4.05.0/build/ocaml/otherlibs/bigarray/bigarray.ml:137: undefined reference to `caml_ba_map_file'
_build/main.native.o: In function `camlBigarray__49':
:(.data+0x67c70): undefined reference to `caml_ba_map_file'
```

### PR DESCRIPTION
**Pull request by talex5**
I don't understand why the build script wants to do things differently for 4.05, but reverting these two changes (erasing `BIGARRAY_OBJ` and `CFLAGS`) allowed hello world to work for me on 4.05!

/cc @avsm

Fixes #194.

### CODE REVIEW

**Comment by talex5** [comment]
Also tested by building mirage-firewall and browsing the web briefly with it. Seems fine!

**Comment by yomimono** [comment]
@avsm Give a shout if you want this reverted.
